//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlipayTradeQueryResponse
    {
        public string TradeNo { get; set; }
        public string AlipayStoreId { get; set; }
        public string BuyerLogonId { get; set; }
        public string BuyerPayAmount { get; set; }
        public string BuyerUserId { get; set; }
        public string DiscountGoodsDetail { get; set; }
        public string IndustrySepcDetail { get; set; }
        public string InvoiceAmount { get; set; }
        public string OpenId { get; set; }
        public string OutTradeNo { get; set; }
        public string PointAmount { get; set; }
        public string ReceiptAmount { get; set; }
        public string SendPayDate { get; set; }
        public string StoreId { get; set; }
        public string StoreName { get; set; }
        public string TerminalId { get; set; }
        public string TotalAmount { get; set; }
        public string TradeStatus { get; set; }
    }
}
